config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'static_pages/home'
  get 'static_pages/help'
  devise_for :users
  namespace :admin do
    resources :users
    resources :static_pages
  end

  resources :categories
  resources :categories do
    member do
      get :new_child
    end
  end

  resources :products do
    resources :images
    member do
      get :list_image
    end
  end



end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent, class_name: Category.name, optional: true
  has_many :children, class_name: Category.name, foreign_key: :parent_id,
           dependent: :destroy

  scope :root_categories, ->{where(parent_id: nil)}

  def is_root?
    parent_id.nil?
  end

  def is_parent?
    !children.empty?
  end

  def self.get_list_path
    arr = all();
    arr.map do |cate|
      {id: cate.id, path: cate.get_path}
    end
  end


  def get_path m_category = self
    m_path = '/' + m_category.name
    loop do
        break if m_category.parent_id.nil?
        m_path.prepend('/' + m_category.parent.name)
        m_category = m_category.parent
      end
    m_path
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "admin/application"
  before_action :load_category, except: %i( index )

  def index
    @category = Category.new
    @categories = Category.root_categories
  end

  def new
    respond_to do |format|
      format.html {redirect_to @category}
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html {redirect_to @category}
      format.js
    end
  end

  def update
    if @category.update_attributes category_params
      respond_to do |format|
        format.html {redirect_to @category}
        format.js
      end
    end
  end

  def new_child
    respond_to do |format|
      format.html {redirect_to @category}
      format.js
    end
  end

  def create
    @category = Category.new category_params
    if @category.save!
      respond_to do |format|
        format.html {redirect_to @category}
        format.js
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html {redirect_to @category}
      format.js
    end
  end

  private

  def category_params
    params.require(:category).permit(:id, :name, :parent_id)
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% if !category.is_parent? %>
  <li id="ct-<%= category.id %>"><%= category.name %> >|
  <%= link_to "add", new_child_category_path(category), remote: true %> |
  <%= link_to "edit", edit_category_path(category), remote: true %> |
  <%= link_to "del", category, method: :delete,
                data: {confirm: "dmm"}, remote: true %>
  </li>
<% else %>
  <li id="ct-<%= category.id %>"><%= category.name %> >|
    <%= link_to "add", new_child_category_path(category), remote: true %> |
    <%= link_to "edit", edit_category_path(category), remote: true %> |
    <%= link_to "del", category, method: :delete,
                data: {confirm: "dmm"}, remote: true %>
    <ul>
      <%= render category.children if category.children.any? %>
    </ul>
  </li>
<% end %>

app/views/categories/_edit.html.erb
<%= form_for @category, remote: true, id: "edit_ct-#{@category.id}" do |f| %>
  <div class="input-group">
    <%= f.text_field :name, class: "form-control", id: "ta-#{@category.id}"  %>
    <span class="input-group-btn">
      <%= f.submit "Okey", class: "btn btn-default btn-success confirm" %>
    </span>
    <span class="input-group-btn">
      <button type="button" class="btn btn-default" id="ed_cancle-<%= @category.id %>">cancle</button>
    </span>
  </div>

<% end %>

app/views/categories/_mcategory.html.erb
<li id="ct-<%= @category.id %>">
  <span>
    <span class="glyphicon glyphicon-file"></span><%= @category.name %>
    <span class="m_span  glyphicon-file"> &gt;|
      <%= link_to "add", new_child_category_path(@category), remote: true %> |
      <%= link_to "edit", edit_category_path(@category), remote: true %>|
      <%= link_to "del", @category, method: :delete,
                  data: {confirm: "dmm"}, remote: true %>
    </span>
  </span>
</li>

app/views/categories/_new_child.html.erb
<% if @category.children.empty? %>
  <li id="ct-<%= @category.id %>" class="parent_li"><span title="collapse">
    <span class="glyphicon glyphicon-folder-open"></span>
      <span class="m_span  glyphicon-file"> <%= @category.name %> &gt;|
        <%= link_to "add", new_child_category_path(@category), remote: true %> |
        <%= link_to "edit", edit_category_path(@category), remote: true %>|
        <%= link_to "del", @category, method: :delete,
                    data: {confirm: "dmm"}, remote: true %>
      </span>
    </span>
    <ul>
      <li id="r-<%= @category.id %>">
  <span>
    <span class="glyphicon glyphicon-file"></span>
    <span class="m_span  glyphicon-file">
      <%= form_for @category.children.build, method: :post, remote: true do |f| %>
        <%= f.hidden_field :parent_id %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <%= f.submit "Add", class: "btn btn-primary" %>
          <button type="button" class="btn btn-default cancel" id="cancle-<%= @category.id %>">cancle</button>
        <% end %>
    </span>
  </span>
      </li>
    </ul>
  </li>
<% else %>
  <li id="r-<%= @category.id %>">
  <span>
    <span class="glyphicon glyphicon-file"></span>
    <span class="m_span  glyphicon-file">
      <%= form_for @category.children.build, method: :post, remote: true do |f| %>
        <%= f.hidden_field :parent_id %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <%= f.submit "Add", class: "btn btn-primary" %>
          <button type="button" class="btn btn-default cancel" id="cancle-<%= @category.id %>">cancle</button>
        <% end %>
    </span>
  </span>
  </li>
<% end %>

app/views/categories/_span.html.erb
<%= @category.name %> &gt;|
<%= link_to "add", new_child_category_path(@category), remote: true %> |
<%= link_to "edit", edit_category_path(@category), remote: true %>|
<%= link_to "del", @category, method: :delete,
            data: {confirm: "dmm"}, remote: true %>

app/views/categories/create.js.erb
<% if @category.is_root? %>
  $("#root").prepend("<%= j render "mcategory" %>");
<% else %>
  $("#r-<%= @category.parent_id %>").replaceWith("<%= j render "mcategory" %>");
<% end %>

app/views/categories/destroy.js.erb
$("#ct-<%= j @category.id.to_s %>").remove();

app/views/categories/edit.js.erb
$('#ct-<%= @category.id %> > span > .m_span').html("<%= j render "edit" %>")
$( "#ed_cancle-<%= @category.id %>" ).click(function() {
    $('#ct-<%= @category.id %> > span > .m_span').html("<%= j render "span" %>");
});

app/views/categories/index.html.erb
<div class="col-md-3">
  <h3 class="text-success">Easy Tree Example</h3>
  <br>
  <div class="easy-tree">
    <div class="easy-tree-toolbar">
      <%= form_for @category, remote: true do |f| %>
      <div class="create">
        <div class="input-group welld">
          <%= f.text_field :name, class: "form-control" %>
          <span class="input-group-btn">
            <%= f.submit "Submit", class: "btn btn-default btn-success confirm" %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
    <ul id="root">
      <%= render @categories %>
    </ul>
  </div>
</div>
<script>
    (function ($) {
        function init() {
            $('.easy-tree').EasyTree({
                addable: true,
                editable: true,
                deletable: true
            });
        }

        window.onload = init();
    })(jQuery)
</script>

app/views/categories/new_child.js.erb
<% if @category.is_parent? %>
  $("#ct-<%= @category.id %> > ul").append("<%= j render "new_child" %>");
<% else %>
  $("#ct-<%= @category.id %>").replaceWith("<%= j render "new_child" %>");
<% end %>
$( "#cancle-<%= @category.id %>" ).click(function() {
    $("#r-<%= @category.id %>").remove();
});

app/views/categories/update.js.erb
$('#ct-<%= @category.id %> > span > .m_span').html("<%= j render "span" %>");